### ISSUE TITLE
Guid uri template path/query parameter values should be normalized to string

### ISSUE THREAD

**Issue by baywet** [microsoft/kiota-abstractions-go#160]
the std uri template library does not handle guids, and wont because it's not a standard API across languages and they don't want to bring on additional dependencies.
We should normalize the value to string (no curlies) before we pass it to the uri template engine.
Originally reported:
https://github.com/std-uritemplate/std-uritemplate/issues/140
https://github.com/microsoft/kiota/issues/4335

Example implementation https://github.com/microsoft/kiota-abstractions-dotnet/blob/5a93d126e9ce30ae332e65f30df7b941e7d7c265/src/RequestInformation.cs#L123

**Comment by michaeldcanady** [comment]
@baywet what about using [go-querystring](https://github.com/michaeldcanady/go-querystring)? it has support for custom encoders. Then any instance of uuid.UUID can be converted to the following type:
```golang
type EncodableUUID struct {
	uuid.UUID
}

func (id EncodableUUID) EncodeValues(key string, v *url.Values) error {
	strId := id.String()
	strId = strings.ReplaceAll(strId, "{", "")
	strId = strings.ReplaceAll(strId, "}", "")
	v.Add(key, strId)

	return nil
}
```
only point of concern I can see if they use the tag "url" instead of "uriparametername".

**Comment by baywet** [comment]
Thanks for following up on this. This is actually already properly handled by the enum case in the normalization.
I have authored #188 to add unit tests that demonstrate it it working as expected.
