### ISSUE TITLE
Group Golang Kiota repositories

### ISSUE THREAD

**Issue by andrueastman** [microsoft/kiota-abstractions-go#170]
Related to https://github.com/microsoft/kiota/issues/4636 and https://github.com/microsoft/kiota-abstractions-dotnet/issues/238

As a language specific concern, we should look into the feasibility of grouping the repos and outline if this is not feasible in this issue.

**Comment by baywet** [comment]
@andrueastman for this one I don't think we can do it since the package namespace and the module distribution are directly mapped to the repo address. I suggest we close this issue to avoid confusion here.

**Comment by andrueastman** [comment]
Thanks @baywet.
