### ISSUE TITLE
Support Models with unknown key names

### ISSUE THREAD

**Issue by michaeldcanady** [microsoft/kiota-abstractions-go#186]
For context I am working on building an SDK for the Service-Now APIs, one of which is basically a dump of a database table, so the keys are unknown prior.

Would it be possible to add a way to support this, additional data doesn't work because the entry has keys as well.

**Comment by michaeldcanady** [comment]
I found a workaround, maybe this is just "the solution" but example code:

```golang
type TableRecord interface {
	Get(string) (RecordElement, error)
	Set(string, RecordElement) error
	serialization.AdditionalDataHolder
	serialization.Parsable
	GetBackingStore() store.BackingStore
	SetBackingStore(store store.BackingStore)
}

type tableRecord struct {
	backingStore store.BackingStore
}

func NewTableRecord() TableRecord {
	return &tableRecord{
		backingStore: store.BackingStoreFactoryInstance(),
	}
}

func CreateTableRecordFromDiscriminatorValue(parseNode serialization.ParseNode) (serialization.Parsable, error) {
	raw, err := parseNode.GetRawValue()
	if err != nil {
		return nil, err
	}
	record, ok := raw.(map[string]interface{})
	if !ok {
		// TODO: define error
		return nil, nil
	}
	tableRecord := NewTableRecord()

	for key, _ := range record {
		tableRecord.Set(key, nil)
	}
	return tableRecord, nil
}

func (tR *tableRecord) GetBackingStore() store.BackingStore {
	return tR.backingStore
}

func (tR *tableRecord) SetBackingStore(store store.BackingStore) {
	tR.backingStore = store
}
func (tR *tableRecord) GetFieldDeserializers() map[string]func(serialization.ParseNode) error {
	fieldDeserializers := map[string]func(serialization.ParseNode) error{}

	for key, _ := range tR.backingStore.Enumerate() {
		fieldDeserializers[key] = func(pn serialization.ParseNode) error {
			tR.GetBackingStore().SetInitializationCompleted(false)
			val, err := pn.GetRawValue()
			if err != nil {
				return nil
			}
			_, ok := val.(map[string]interface{})
			var elem RecordElement
			if !ok {
				elem = NewRecordElement()
				if err := elem.SetValue(val); err != nil {
					return err
				}
			} else {
				var ok bool
				rawElem, err := pn.GetObjectValue(CreateRecordElementFromDiscriminatorValue)
				if err != nil {
					return err
				}
				elem, ok = rawElem.(RecordElement)
				if !ok {
					// TODO: define error
					return nil
				}
			}
			if err := tR.Set(key, elem); err != nil {
				return err
			}
			tR.GetBackingStore().SetInitializationCompleted(true)
			return nil
		}
	}

	return fieldDeserializers
}
```

**Comment by baywet** [comment]
Hi @michaeldcanady 
Thank you for using kiota and for reaching out.
I can see you've found a solution to your problem.
Let us know if you have any additional comments or questions.

**Comment by michaeldcanady** [comment]
Hi @baywet 
I thought of this more as a workaround since the object is needing to be read twice (once to get the fields, and again to populate them). I’d think a better solution would be to provide a default in the GetFieldDeserializers method (which isn’t supported) or something like how the additional data is handled. Thoughts?

**Comment by baywet** [comment]
Thank you for the additional information.
I'm still trying to figure out what problem are you trying to solve here.

I'm guessing you have a endpoint that returns tables.
Tables have a variable set of rows, which means they are not schematized ahead of time in the description.
Is this correct?

That probably means you're currently accessing those thanks to the additional properties field.

But then I don't have enough elements to understand what's challenging beyond that?
Can you provide additional context here please?

**Comment by baywet** [comment]
Do you mean something like updating all the values regardless of the key? No this isn't supported today.

Let us know if you have any additional comments or questions.

**Comment by michaeldcanady** [comment]
I thinking more like a default dictionary, where if a key doesn’t exist with in the FieldDeserializers map then it calls the deserializer.
Hopefully this is making some sense, it’s a pretty ambiguous idea… and tbh I don’t have a concrete idea of how just a rough one for behavior 😅

**Comment by baywet** [comment]
Thank you for the additional information.

Are you saying you'd like to "inject" additional deserializers? As opposed to simply using the additional properties map/field?

**Comment by michaeldcanady** [comment]
I think that would be more accurate yes, because it’s not “additional” in the sense that it needs to be separate from the other fields, it’s a parsable without the fields being know prior to the deserialization being started.

**Comment by michaeldcanady** [comment]
To my understanding it can’t use it to write directly to the backed store, I’d have to store the data in a field like “additionalData” which has a nested map.

**Comment by michaeldcanady** [comment]
The "issue" with utilizing the additional data field is I'd need all methods to fetch from it, so essentially having all the store values inside the `additionalValue` field and these aren't _technically_ additional values they objects are just dynamic, from instance to instance.

**Comment by baywet** [comment]
Thank you for the additional information.

Since the additional values are a map, can't you simply iterate over the keys with a range operator? Or am I missing something?

**Comment by michaeldcanady** [comment]
The keys could be iterated over, however, it would be:
1. Iterate over keys
2. Add each key to store
3. Remove `additionalData` field

**Comment by baywet** [comment]
Thank you for the additional information.

I'm not sure what would be the next step here? What you want to to (accessing dynamic fields) is already possible today. Kiota wouldn't be able to generate them since by definition they are not part of the OpenAPI description. Accessing them with "Additional Data" is the right thing to do even if the name is not the most straightforward one (as we know, naming is difficult).
