### ISSUE TITLE
Support For Parsing Headers

### ISSUE THREAD

**Issue by michaeldcanady** [microsoft/kiota-abstractions-go#187]
I'm working on an SDK for the ServiceNow APIs, they store their next, previous, first, and last links in the response headers. Is this something that Kiota supports, will support, or are considering supporting?

**Comment by baywet** [comment]
Hi @michaeldcanady 
Thank you for using kiota and for reaching out.

Have you tried using [the headers inspection option](https://github.com/microsoft/kiota-http-go/blob/5beb0cfc3f971db7c6ff1342b22d601b04eccd30/headers_inspection_handler.go#L13) and passing it as part of the request configuration?

Let us know if you have any additional comments or questions.

**Comment by michaeldcanady** [comment]
I hadn't considered using this! I'll try it out and reach back out. thank you!

**Comment by baywet** [comment]
No worries, closing for now. Feel free to re-open if needed.
