### ISSUE TITLE
Add Support for content types that use * wildcard

### ISSUE THREAD

**Issue by michaeldcanady** [microsoft/kiota-abstractions-go#189]
the * wildcard is supported in valid content type formats (ex: */* and image/*) but the current implementation of ParseNodeFactoryRegistry doesn't support it.

**Comment by baywet** [comment]
Hi @michaeldcanady 
Thank you for using kiota and for reaching out.
We're having what I think is the same conversation over here. https://github.com/microsoft/kiota-dotnet/issues/471
Do you mind joining there? I'll go ahead and close this one for now.
