### ISSUE TITLE
The factory type should be corrected

### ISSUE THREAD

**Issue by baywet** [microsoft/kiota-abstractions-go#61]
https://github.com/microsoft/kiota-abstractions-go/blob/93aa823a50eda38e35b97e2d95a7c17f1a3b92d5/store/backing_store_factory.go#L9

- [ ] the type of the variable should be BackingStoreFactory and not InMemoryBacking store
- [ ] the generation needs to be corrected to call the factory (add () )

With the current code, we're going to end up with one backing store for all objects in memory, and they'll end up overwriting each other, sorry I didn't catch that earlier.

**Comment by rkodev** [comment]
@baywet Corrected the type to be of type `BackingStoreFactory`, currently `NewInMemoryBackingStore` is of type `func() BackingStore`, which is invoked for all the entites. I do not think in this case the generation will need correction since every entity has its own instance of the backingstore
