### ISSUE TITLE
concurrent map writes in github.com/microsoft/kiota-abstractions-go/api_client_builder.go:70

### ISSUE THREAD

**Issue by mblaschke** [microsoft/kiota-abstractions-go#75]
This happened only one time but i had a concurrent map write here:
https://github.com/microsoft/kiota-abstractions-go/blob/main/api_client_builder.go#L70

at that time i was using ``serviceClient.DirectoryObjects().GetByIds().Post(ctx, requestBody, nil)`` from msgraph-sdk

```
goroutine 113 [running]:
github.com/microsoft/kiota-abstractions-go.enableBackingStoreForParseNodeRegistry(0x106986768)
	/Users/mblaschke/Projects/webdevops/azure-resourcemanager-exporter/vendor/github.com/microsoft/kiota-abstractions-go/api_client_builder.go:70 +0xb0
github.com/microsoft/kiota-abstractions-go.EnableBackingStoreForParseNodeFactory({0x105d1bd90?, 0x106986768})
	/Users/mblaschke/Projects/webdevops/azure-resourcemanager-exporter/vendor/github.com/microsoft/kiota-abstractions-go/api_client_builder.go:59 +0x44
github.com/microsoft/kiota-http-go.(*NetHttpRequestAdapter).EnableBackingStore(0x140002239f0, 0x105d12268)
	/Users/mblaschke/Projects/webdevops/azure-resourcemanager-exporter/vendor/github.com/microsoft/kiota-http-go/nethttp_request_adapter.go:106 +0x34
github.com/microsoftgraph/msgraph-sdk-go.NewGraphBaseServiceClient({0x105d30370, 0x140002239f0}, 0x0?)
	/Users/mblaschke/Projects/webdevops/azure-resourcemanager-exporter/vendor/github.com/microsoftgraph/msgraph-sdk-go/graph_base_service_client.go:246 +0x294
github.com/microsoftgraph/msgraph-sdk-go.NewGraphServiceClient(...)
	/Users/mblaschke/Projects/webdevops/azure-resourcemanager-exporter/vendor/github.com/microsoftgraph/msgraph-sdk-go/graph_service_client.go:17
github.com/microsoftgraph/msgraph-sdk-go.NewGraphServiceClientWithCredentialsAndHosts({0x105d19140?, 0x14000124920?}, {0x140000a3698?, 0x1057e9ccc?, 0x0?}, {0x0?, 0x0?, 0x0?})
	/Users/mblaschke/Projects/webdevops/azure-resourcemanager-exporter/vendor/github.com/microsoftgraph/msgraph-sdk-go/graph_service_client.go:52 +0x144
github.com/webdevops/go-common/msgraphsdk/msgraphclient.(*MsGraphClient).ServiceClient(0x14000172380)

[...]

goroutine 115 [runnable]:
github.com/microsoft/kiota-abstractions-go.(*RequestInformation).setRequestType(0x140004e6b00?, {0x105bfb000?, 0x1400060e660?}, {0x105d2f898, 0x1400072e6e0})
	/Users/mblaschke/Projects/webdevops/azure-resourcemanager-exporter/vendor/github.com/microsoft/kiota-abstractions-go/request_information.go:197 +0xf0
github.com/microsoft/kiota-abstractions-go.(*RequestInformation).SetContentFromParsable(0x14000690810?, {0x105d2b040, 0x1400012a120}, {0x105d30370, 0x1400072e640}, {0x1057f46de, 0x10}, {0x13060b418?, 0x1400060e660?})
	/Users/mblaschke/Projects/webdevops/azure-resourcemanager-exporter/vendor/github.com/microsoft/kiota-abstractions-go/request_information.go:214 +0x208
github.com/microsoftgraph/msgraph-sdk-go/directoryobjects.(*GetByIdsRequestBuilder).ToPostRequestInformation(0x140005e3848, {0x105d2b040, 0x1400012a120}, {0x105d2fa88?, 0x1400060e660}, 0x0)
	/Users/mblaschke/Projects/webdevops/azure-resourcemanager-exporter/vendor/github.com/microsoftgraph/msgraph-sdk-go/directoryobjects/get_by_ids_request_builder.go:62 +0x1e8
github.com/microsoftgraph/msgraph-sdk-go/directoryobjects.(*GetByIdsRequestBuilder).Post(0x140000e9848, {0x105d2b040, 0x1400012a120}, {0x105d2fa88?, 0x1400060e660?}, 0x104da8b84?)
	/Users/mblaschke/Projects/webdevops/azure-resourcemanager-exporter/vendor/github.com/microsoftgraph/msgraph-sdk-go/directoryobjects/get_by_ids_request_builder.go:38 +0x30

```

using ``go version go1.20.2 darwin/arm64``

go.mod:
```
	github.com/microsoftgraph/msgraph-sdk-go v0.60.0
	github.com/microsoftgraph/msgraph-sdk-go-core v0.36.0
	github.com/microsoft/kiota-abstractions-go v0.19.0
	github.com/microsoft/kiota-authentication-azure-go v0.6.0 // indirect
	github.com/microsoft/kiota-http-go v0.16.1 // indirect
	github.com/microsoft/kiota-serialization-form-go v0.9.0 // indirect
	github.com/microsoft/kiota-serialization-json-go v0.9.0 // indirect
	github.com/microsoft/kiota-serialization-text-go v0.7.0 // indirect
```

**Comment by mblaschke** [comment]
not sure, because I'm not used to this library and I don't have a clue where and how to implement the lock here and how big the performance impact might be 🤔

should the lock be part of ParseNodeFactoryRegistry? or outside?

**Comment by baywet** [comment]
Locks are actually already implemented at the factory level, but the enable backing store function is not making use of them.

https://github.com/microsoft/kiota-abstractions-go/blob/e9187475538f2d68bcf91d64fd11302fecbbca4e/api_client_builder.go#L70

in the if block, the enable method needs to call block and unblock.

https://github.com/microsoft/kiota-abstractions-go/blob/e9187475538f2d68bcf91d64fd11302fecbbca4e/api_client_builder.go#L11

As per the perf impact, this should be limited to creating the first client in the app domain.

**Comment by FabianTe** [comment]
@baywet As you mentioned in https://github.com/microsoftgraph/msgraph-sdk-go/issues/54 I'd like to give fixing this a try. Looking at `api_client_builder` I noticed that there may be two primary places where concurrent access to maps should be investigated?

https://github.com/microsoft/kiota-abstractions-go/blob/e9187475538f2d68bcf91d64fd11302fecbbca4e/api_client_builder.go#L47-L50

https://github.com/microsoft/kiota-abstractions-go/blob/e9187475538f2d68bcf91d64fd11302fecbbca4e/api_client_builder.go#L67-L70

Both `registry` objects (`SerializationWriterFactoryRegistry` and `ParseNodeFactoryRegistry` respectively) contain one map from content type to a factory.

AFAIK your idea is to use the package level lock you linked (`var deserializerMutex sync.Mutex`) to ensure that both `enable...` funcs do not write to the maps concurrently?

I may have very different experiences with implementing locks but to me it seems like the locks should better be part of `SerializationWriterFactoryRegistry` and `ParseNodeFactoryRegistry` respectively? I get that `DefaultSerializationWriterFactoryInstance` and `DefaultSerializationWriterFactoryInstance` are probably the objects being manipulated but why not have these locks on the structs?

Just asking to get a bit more information about this. I can of course simply try to code up *some* solution, right now I would refactor the lock usage. Or at least use new locks on the named structs.

**Comment by FabianTe** [comment]
> it would make more sense to have the locks on the structs and refactor things accordingly. We want to keep those locks private however, to prevent consumer code from impacting the behavior here.

I get that. Regarding a potential fix: Shall i just add a new lock for the given functions? Then they would essentially protect every call to the `enable...` functions across all structs. Compared to refactoring all usages of the named maps this may be a simpler fix. Up to you to decide.

I am not using kiota myself. Is my assumption correct that the code we talk about here is mostly for initialization and will therefore be called _"a few times" (compared to the actual API call methods performed by the generated clients)_?

**Comment by baywet** [comment]
I'm not sure I'm following the distinction here? (first paragraph) I believe the best way forward would probably to send a PR our way and iterate on that.

Your assumption is correct.
